- name: Show Docker Compose Running Status
  hosts: all
  become: true
  become_user: root
  vars:
    docker_compose_dir: /home/ubuntu
    secret_name: prod/rdsuser/a11yvillage
    secret_region: ap-northeast-1
    webroot_path: '/var/www/html'  # the root path of your site
    certbot_source_directory: /usr/local/certbot-src
    certbot_executable_path: "{{ certbot_source_directory }}/venv/bin/certbot"
    domain: tmp.a11yvillage.coseeing.org
    email: tsengwoody@coseeing.org
  collections:
    - community.docker
    - community.aws
  tasks:

    - name: Set ansible_python_interpreter to use the installed Python
      set_fact:
        ansible_python_interpreter: /usr/bin/python3

    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      become: true

    - name: Upgrade all apt packages
      apt: upgrade=yes force_apt_get=yes
      become: true

    - name: Install Python pip
      apt: name={{ item }} update_cache=true state=present force_apt_get=yes
      with_items:
        - python3-pip
      become: true

    - name: Install Python packages using apt
      apt:
        name:
          - python3-docker
          - python3-boto3
          - python3-botocore
          - python3-venv
          - gcc
          - libaugeas0
          - libssl-dev
          - libffi-dev
          - ca-certificates
          - openssl
          - git
        state: present
        update_cache: yes
      become: true

    - name: Install Docker dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes
      become: true

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
      become: true

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      become: true

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: true

    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
      become: true

    - name: Clone the certbot source directory
      ansible.builtin.git:
        depth: 1
        repo: https://github.com/certbot/certbot
        dest: "{{ certbot_source_directory }}"
        update: true

    - name: Create certbot in virtual environment
      ansible.builtin.command: python3 tools/venv.py
      args:
        chdir: "{{ certbot_source_directory }}"

    - name: Generate the SSL certificate
      ansible.builtin.command: "{{ certbot_executable_path }} --nginx -d {{ domain }} -d {{ tmp_domain }} --non-interactive --agree-tos --email {{ email }}"

    - name: Set up automatic renewal
      ansible.builtin.cron:
        name: "Certbot automatic renewal"
        job: "{{ certbot_executable_path }} renew --quiet"
        minute: "11"
        hour: "11"

    - name: Create Nginx configuration for domain
      copy:
        dest: /etc/nginx/sites-available/{{ domain }}
        content: |
          server {
              listen 80;
              server_name {{ domain }};
              
              location / {
                  return 301 https://$host$request_uri;
              }
          }

          server {
              listen 443 ssl;
              server_name {{ domain }};

              ssl_certificate /etc/letsencrypt/live/{{ domain }}/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/{{ domain }}/privkey.pem;

              location / {
                  proxy_pass http://localhost:3000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Create symbolic links for Nginx sites
      file:
        src: "/etc/nginx/sites-available/{{ domain }}"
        dest: "/etc/nginx/sites-enabled/{{ domain }}"
        state: link

    - name: Remove default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Copy docker-compose.yml Document
      copy:
        dest: "{{ docker_compose_dir }}/docker-compose.yml"
        content: |
          services:
            a11yvillage-web:
              container_name: a11yvillage-web
              image: 622913514517.dkr.ecr.ap-northeast-1.amazonaws.com/a11yvillage-web:latest
              restart: always
              ports:
                - "3000:3000"
              environment:
                - NEXT_PUBLIC_API_URL=https://api.a11yvillage.coseeing.org/
                - NEXT_PUBLIC_RESOURCE_URL=https://a11yvillage.s3.ap-northeast-1.amazonaws.com/

    - name: Update the repository cache and update package "unzip" to latest version using default
      apt:
        name: unzip
        state: latest
        update_cache: yes

    - name: Install AWS CLI v2
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
        unzip /tmp/awscliv2.zip -d /tmp
        sudo /tmp/aws/install
        rm -f /tmp/awscliv2.zip
        rm -rf /tmp/aws
      args:
        creates: /usr/local/bin/aws

    - name: Login ECR using AWS CLI
      shell: |
        aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 622913514517.dkr.ecr.ap-northeast-1.amazonaws.com
      register: ecr_login
      no_log: false

    - name: Run
      docker_compose_v2:
        project_src: "{{ docker_compose_dir }}"
        state: present
      register: compose_result

    - name: Show compose_result Detail info
      debug:
        var: compose_result

    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: true