- name: Show Docker Compose Running Status
  hosts: ec2
  become: true
  become_user: root
  collections:
    - community.docker
  tasks:
    - name: Install docker Python library
      pip:
        name: docker
        executable: pip3

    - name: Get Running Status
      docker_compose_v2:
        project_src: /workspace/a11yvillageCrontab/avc
        state: present
      register: compose_result

    - name: Show compose_result Detail info
      debug:
        var: compose_result
