- name: Show Docker Compose Running Status
  hosts: ec2
  become: true
  become_user: root
  collections:
    - community.docker
  tasks:
    - name: Get Running Status
      docker_compose:
        project_src: /workspace/a11yvillageCrontab/avc
        state: present
      register: compose_result

    - name: Show Running Status
      debug:
        msg: |
          Service Status：
          {% for service in compose_result.services %}
          - {{ service.service }}: {{ service.current_state }}
          {% endfor %}