---
- name: Reload course OpenVPN
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/reload-openvpn.yml"

- name: Reload course firewall
  ansible.builtin.systemd_service:
    name: openvpn-course-firewall
    state: reloaded
    daemon_reload: true
