name: A11yVillage Production Deploy

on:
  workflow_dispatch:
    inputs:
      deployTag:
        description: "tag to deploy"
        required: true
        type: string

jobs:
  deployment:
    environment: a11y-village-production
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ACTION_ROLE }}
          aws-region: ap-northeast-1

      - name: Render AWS ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{vars.TASK_DEFINITION_PATH}}
          container-name: a11y-village-production
          image: ${{vars.ECR_ARN}}/demo-node-app:${{github.event.inputs.deployTag}}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{vars.ECS_SERVICE}}
          cluster: ${{vars.ECS_CLUSTER}}
          wait-for-service-stability: true
